# sudo: required
dist: trusty
language: python
python:
  - "3.9"

services:
  - docker

install:
  - pip install --upgrade pytest pytest-cov coveralls pydenticon pandas
  - pip install -e .

script:
  - python -m pytest -v --cov blabel --cov-report term-missing
  
after_success:
  - coveralls
